name: StreamyStats
version: 1.0.0
slug: streamystats
description: StreamyStats Home Assistant Add-on
url: https://github.com/matzewr/ha-addons
webui: http://[HOST]:[PORT:3000]
arch:
  - amd64
  - aarch64
init: false
map:
  - data:rw
options:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: streamystats
  SESSION_SECRET: your-session-secret
  NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: your-encryption-key
schema:
  POSTGRES_USER: str
  POSTGRES_PASSWORD: str
  POSTGRES_DB: str
  SESSION_SECRET: str
  NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: str
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: StreamyStats Web Interface
image: ghcr.io/matzewr/streamystats