name: NZBHydra2 mit Gluetun VPN
version: "1.0.0"
description: "NZBHydra2 Addon mit Gluetun VPN (WireGuard) Tunnel."
startup: services
boot: auto
init: false
host_network: false
privileged:
  - NET_ADMIN
  - SYS_MODULE
map:
  - config:rw
  - ssl
  - addons:rw
  - backup:rw
  - share:rw
options:
  use_conf_file: false
  wg_private_key: ""
  wg_address: ""
  wg_dns: ""
  wg_public_key: ""
  wg_allowed_ips: ""
  wg_endpoint: ""
schema:
  use_conf_file: bool?
  wg_private_key: str?
  wg_address: str?
  wg_dns: str?
  wg_public_key: str?
  wg_allowed_ips: str?
  wg_endpoint: str?
  conf_file: str? # base64 encoded file, if supported
